/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcode-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Barcode Codes */
        get: operations["list_barcode_codes_api_barcode_codes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcode-codes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Barcode Code */
        get: operations["get_barcode_code_api_barcode_codes__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Barcode Numbers */
        post: operations["create_barcode_numbers_api_barcodes_numbers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Barcode Lifecycle Items */
        get: operations["get_barcode_lifecycle_items_api_barcodes_lifecycle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/{barcode}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Barcode Detail Endpoint */
        get: operations["get_barcode_detail_endpoint_api_barcodes__barcode__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/{barcode}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Barcode Endpoint */
        post: operations["cancel_barcode_endpoint_api_barcodes__barcode__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/{barcode}/mark-used": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Barcode Used Endpoint */
        post: operations["mark_barcode_used_endpoint_api_barcodes__barcode__mark_used_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/history/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation Batches */
        get: operations["get_generation_batches_api_barcodes_history_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/history/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation Batch Detail */
        get: operations["get_generation_batch_detail_api_barcodes_history_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/history/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Generated Barcode */
        get: operations["search_generated_barcode_api_barcodes_history_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/my-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Batches */
        get: operations["get_my_batches_api_barcodes_my_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/my-batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Batch Detail */
        get: operations["get_my_batch_detail_api_barcodes_my_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/my-print-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Print History */
        get: operations["get_my_print_history_api_barcodes_my_print_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/batches/{batch_id}/pdf-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Batch Pdf */
        get: operations["preview_batch_pdf_api_barcodes_batches__batch_id__pdf_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/batches/{batch_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Print Batch Pdf */
        post: operations["print_batch_pdf_api_barcodes_batches__batch_id__pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcodes/print-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Print History */
        get: operations["get_print_history_api_barcodes_print_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clients */
        get: operations["get_clients_api_clients_get"];
        put?: never;
        /** Create Client Endpoint */
        post: operations["create_client_endpoint_api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client Endpoint */
        get: operations["get_client_endpoint_api_clients__client_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Client Endpoint */
        patch: operations["update_client_endpoint_api_clients__client_id__patch"];
        trace?: never;
    };
    "/api/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Departments */
        get: operations["get_departments_api_departments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Department Tree */
        get: operations["get_department_tree_api_departments_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/range-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Range Requests */
        get: operations["get_range_requests_api_range_requests_get"];
        put?: never;
        /** Create Range Request Endpoint */
        post: operations["create_range_request_endpoint_api_range_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/range-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Range Request Endpoint */
        get: operations["get_range_request_endpoint_api_range_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/range-requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Range Request Endpoint */
        post: operations["approve_range_request_endpoint_api_range_requests__request_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/range-requests/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Range Request Endpoint */
        post: operations["reject_range_request_endpoint_api_range_requests__request_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/range-requests/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Range Request Endpoint */
        post: operations["cancel_range_request_endpoint_api_range_requests__request_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranges/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Ranges */
        get: operations["get_my_ranges_api_ranges_my_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ranges */
        get: operations["get_ranges_api_ranges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranges/{range_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate From Range Endpoint */
        post: operations["generate_from_range_endpoint_api_ranges__range_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranges/{range_id}/remaining": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Range Remaining Endpoint */
        get: operations["get_range_remaining_endpoint_api_ranges__range_id__remaining_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranges/{range_id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Range Batches */
        get: operations["get_range_batches_api_ranges__range_id__batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranges/{range_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Range Endpoint */
        get: operations["get_range_endpoint_api_ranges__range_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User Endpoint */
        post: operations["create_user_endpoint_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Endpoint */
        get: operations["get_user_endpoint_api_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Endpoint */
        patch: operations["update_user_endpoint_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Logs */
        get: operations["get_audit_logs_api_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditLogItem */
        AuditLogItem: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            /** Username */
            username: string | null;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string | null;
            /** Entity Id */
            entity_id: string | null;
            /** Ip Address */
            ip_address: string | null;
            /** User Agent */
            user_agent: string | null;
            /** Details */
            details: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BarcodeCancelRequest */
        BarcodeCancelRequest: {
            /** Reason */
            reason: string;
        };
        /** BarcodeCodeRead */
        BarcodeCodeRead: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Category */
            category: string | null;
            /** Status */
            status: string;
            /** Owner */
            owner: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BarcodeDepartmentInfo */
        BarcodeDepartmentInfo: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Region */
            region: string;
        };
        /** BarcodeDetailResponse */
        BarcodeDetailResponse: {
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Barcode */
            barcode: string;
            /** Package Type */
            package_type: string;
            /** Department Id */
            department_id: number | null;
            /** Range Id */
            range_id?: number | null;
            /** Sequence Number */
            sequence_number: number;
            /** Printed */
            printed: boolean;
            /** Printed At */
            printed_at: string | null;
            /**
             * Status
             * @default generated
             */
            status: string;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Cancelled By */
            cancelled_by?: string | null;
            /** Cancellation Reason */
            cancellation_reason?: string | null;
            /** Used At */
            used_at?: string | null;
            /** Used By */
            used_by?: string | null;
            /** Usage Notes */
            usage_notes?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            batch: components["schemas"]["GeneratedBatchItem"];
            range?: components["schemas"]["BarcodeRangeInfo"] | null;
            department?: components["schemas"]["BarcodeDepartmentInfo"] | null;
        };
        /** BarcodeLifecycleListResponse */
        BarcodeLifecycleListResponse: {
            /** Items */
            items: components["schemas"]["GeneratedBarcodeItem"][];
            /** Count */
            count: number;
        };
        /** BarcodeMarkUsedRequest */
        BarcodeMarkUsedRequest: {
            /** Notes */
            notes?: string | null;
        };
        /** BarcodeNumberRequest */
        BarcodeNumberRequest: {
            /** Package Type */
            package_type: string;
            /** Quantity */
            quantity: number;
            /** Department Id */
            department_id?: number | null;
            /** Generated By */
            generated_by?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** BarcodeNumberResponse */
        BarcodeNumberResponse: {
            /** Batch Id */
            batch_id: number;
            /** Items */
            items: string[];
            /** Count */
            count: number;
            /** First Barcode */
            first_barcode: string;
            /** Last Barcode */
            last_barcode: string;
        };
        /** BarcodeRangeInfo */
        BarcodeRangeInfo: {
            /** Id */
            id: number;
            /** Package Type */
            package_type: string;
            /** Start Number */
            start_number: number;
            /** End Number */
            end_number: number;
            /** Current Number */
            current_number: number;
            /** Status */
            status: string;
        };
        /** BarcodeRangeRead */
        BarcodeRangeRead: {
            /** Id */
            id: number;
            /** Package Type */
            package_type: string;
            /** Start Number */
            start_number: number;
            /** End Number */
            end_number: number;
            /** Current Number */
            current_number: number;
            /** Status */
            status: string;
            /** Issued To Client Id */
            issued_to_client_id: number | null;
            /** Issued To Department Id */
            issued_to_department_id: number | null;
            /** Request Id */
            request_id: number | null;
            /** Issued By */
            issued_by: number | null;
            /** Issued At */
            issued_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Body_login_api_auth_login_post */
        Body_login_api_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Name */
            name: string;
            /** Contact Person */
            contact_person?: string | null;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Email */
            email?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ClientRead */
        ClientRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Contact Person */
            contact_person: string | null;
            /** Contact Phone */
            contact_phone: string | null;
            /** Email */
            email: string | null;
            /** Notes */
            notes: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Name */
            name?: string | null;
            /** Contact Person */
            contact_person?: string | null;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Email */
            email?: string | null;
            /** Notes */
            notes?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** DepartmentItem */
        DepartmentItem: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Region */
            region: string;
            /** Parent Id */
            parent_id: number | null;
            /** Department Type */
            department_type: string | null;
            /** Full Path */
            full_path: string | null;
        };
        /** DepartmentTreeItem */
        DepartmentTreeItem: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Department Type */
            department_type: string | null;
            /** Full Path */
            full_path: string | null;
            /** Children */
            children: components["schemas"]["DepartmentTreeItem"][];
        };
        /** GeneratedBarcodeItem */
        GeneratedBarcodeItem: {
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Barcode */
            barcode: string;
            /** Package Type */
            package_type: string;
            /** Department Id */
            department_id: number | null;
            /** Range Id */
            range_id?: number | null;
            /** Sequence Number */
            sequence_number: number;
            /** Printed */
            printed: boolean;
            /** Printed At */
            printed_at: string | null;
            /**
             * Status
             * @default generated
             */
            status: string;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Cancelled By */
            cancelled_by?: string | null;
            /** Cancellation Reason */
            cancellation_reason?: string | null;
            /** Used At */
            used_at?: string | null;
            /** Used By */
            used_by?: string | null;
            /** Usage Notes */
            usage_notes?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** GeneratedBarcodeSearchResponse */
        GeneratedBarcodeSearchResponse: {
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Barcode */
            barcode: string;
            /** Package Type */
            package_type: string;
            /** Department Id */
            department_id: number | null;
            /** Range Id */
            range_id?: number | null;
            /** Sequence Number */
            sequence_number: number;
            /** Printed */
            printed: boolean;
            /** Printed At */
            printed_at: string | null;
            /**
             * Status
             * @default generated
             */
            status: string;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Cancelled By */
            cancelled_by?: string | null;
            /** Cancellation Reason */
            cancellation_reason?: string | null;
            /** Used At */
            used_at?: string | null;
            /** Used By */
            used_by?: string | null;
            /** Usage Notes */
            usage_notes?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            batch: components["schemas"]["GeneratedBatchItem"];
        };
        /** GeneratedBatchDetail */
        GeneratedBatchDetail: {
            /** Id */
            id: number;
            /** Package Type */
            package_type: string;
            /** Quantity */
            quantity: number;
            /** First Barcode */
            first_barcode: string;
            /** Last Barcode */
            last_barcode: string;
            /** Department Id */
            department_id: number | null;
            /** Range Id */
            range_id?: number | null;
            /** Generated By */
            generated_by: string | null;
            /** Source */
            source: string | null;
            /** Status */
            status: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Notes */
            notes: string | null;
            /** Barcodes */
            barcodes: components["schemas"]["GeneratedBarcodeItem"][];
        };
        /** GeneratedBatchItem */
        GeneratedBatchItem: {
            /** Id */
            id: number;
            /** Package Type */
            package_type: string;
            /** Quantity */
            quantity: number;
            /** First Barcode */
            first_barcode: string;
            /** Last Barcode */
            last_barcode: string;
            /** Department Id */
            department_id: number | null;
            /** Range Id */
            range_id?: number | null;
            /** Generated By */
            generated_by: string | null;
            /** Source */
            source: string | null;
            /** Status */
            status: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Notes */
            notes: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PrintBatchRequest */
        PrintBatchRequest: {
            /** Printed By */
            printed_by?: string | null;
            /** Printer Name */
            printer_name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PrintedBatchItem */
        PrintedBatchItem: {
            /** Id */
            id: number;
            /** Generated Batch Id */
            generated_batch_id: number;
            /** Department Id */
            department_id: number | null;
            /** Printed Count */
            printed_count: number;
            /** First Barcode */
            first_barcode: string;
            /** Last Barcode */
            last_barcode: string;
            /** Printed By */
            printed_by: string | null;
            /** Printer Name */
            printer_name: string | null;
            /** Status */
            status: string;
            /**
             * Printed At
             * Format: date-time
             */
            printed_at: string;
            /** Notes */
            notes: string | null;
        };
        /** RangeGenerateRequest */
        RangeGenerateRequest: {
            /** Quantity */
            quantity: number;
            /** Notes */
            notes?: string | null;
        };
        /** RangeRemainingResponse */
        RangeRemainingResponse: {
            /** Range Id */
            range_id: number;
            /** Remaining */
            remaining: number;
            /** Current Number */
            current_number: number;
            /** End Number */
            end_number: number;
            /** Status */
            status: string;
        };
        /** RangeRequestCreate */
        RangeRequestCreate: {
            /** Purpose */
            purpose: string;
            /** Requested Quantity */
            requested_quantity: number;
            /** Department Id */
            department_id: number;
            /** Requested Code */
            requested_code?: string | null;
            /** Package Type */
            package_type?: string | null;
            /** Client Id */
            client_id?: number | null;
            /**
             * Request Type
             * @default issue_range
             */
            request_type: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Notes */
            notes?: string | null;
        };
        /** RangeRequestDecision */
        RangeRequestDecision: {
            /** Approved Code */
            approved_code?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** RangeRequestRead */
        RangeRequestRead: {
            /** Id */
            id: number;
            /** Requester Id */
            requester_id: number;
            /** Client Id */
            client_id: number | null;
            /** Department Id */
            department_id: number | null;
            /** Package Type */
            package_type: string | null;
            /** Requested Quantity */
            requested_quantity: number;
            /** Request Type */
            request_type: string;
            /** Purpose */
            purpose: string | null;
            /** Requested Code */
            requested_code: string | null;
            /** Approved Code */
            approved_code: string | null;
            /** Decision Notes */
            decision_notes: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Handled By */
            handled_by: number | null;
            /** Handled At */
            handled_at: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role: string;
            /** Department Id */
            department_id?: number | null;
            /** Client Id */
            client_id?: number | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string | null;
            /** Role */
            role: string;
            /** Department Id */
            department_id: number | null;
            /** Client Id */
            client_id: number | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role?: string | null;
            /** Department Id */
            department_id?: number | null;
            /** Client Id */
            client_id?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_barcode_codes_api_barcode_codes_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeCodeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_barcode_code_api_barcode_codes__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeCodeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_barcode_numbers_api_barcodes_numbers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeNumberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeNumberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_barcode_lifecycle_items_api_barcodes_lifecycle_get: {
        parameters: {
            query?: {
                status?: string | null;
                package_type?: string | null;
                department_id?: number | null;
                printed?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeLifecycleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_barcode_detail_endpoint_api_barcodes__barcode__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                barcode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_barcode_endpoint_api_barcodes__barcode__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                barcode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBarcodeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_barcode_used_endpoint_api_barcodes__barcode__mark_used_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                barcode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeMarkUsedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBarcodeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_batches_api_barcodes_history_batches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                package_type?: string | null;
                department_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBatchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_batch_detail_api_barcodes_history_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_generated_barcode_api_barcodes_history_search_get: {
        parameters: {
            query: {
                barcode: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBarcodeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_batches_api_barcodes_my_batches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBatchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_batch_detail_api_barcodes_my_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_print_history_api_barcodes_my_print_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrintedBatchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_batch_pdf_api_barcodes_batches__batch_id__pdf_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    print_batch_pdf_api_barcodes_batches__batch_id__pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrintBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_print_history_api_barcodes_print_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                department_id?: number | null;
                generated_batch_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrintedBatchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clients_api_clients_get: {
        parameters: {
            query?: {
                search?: string | null;
                limit?: number;
                offset?: number;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_endpoint_api_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_endpoint_api_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_endpoint_api_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_departments_api_departments_get: {
        parameters: {
            query?: {
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_department_tree_api_departments_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentTreeItem"][];
                };
            };
        };
    };
    get_range_requests_api_range_requests_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
                package_type?: string | null;
                client_id?: number | null;
                department_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeRequestRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_range_request_endpoint_api_range_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RangeRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_range_request_endpoint_api_range_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_range_request_endpoint_api_range_requests__request_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RangeRequestDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_range_request_endpoint_api_range_requests__request_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RangeRequestDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_range_request_endpoint_api_range_requests__request_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RangeRequestDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_ranges_api_ranges_my_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeRangeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ranges_api_ranges_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                package_type?: string | null;
                status?: string | null;
                client_id?: number | null;
                department_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeRangeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_from_range_endpoint_api_ranges__range_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                range_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RangeGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeNumberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_range_remaining_endpoint_api_ranges__range_id__remaining_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                range_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeRemainingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_range_batches_api_ranges__range_id__batches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                range_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedBatchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_range_endpoint_api_ranges__range_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                range_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarcodeRangeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_endpoint_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_endpoint_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_endpoint_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_logs_api_audit_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                action?: string | null;
                username?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
