import { FileText, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import { getBatchDetail } from "../api/barcodesApi";
import { getErrorMessage } from "../api/http";
import type { GeneratedBatchDetail } from "../api/types";
import { Badge } from "../components/Badge";
import { Button } from "../components/Button";
import { EmptyState } from "../components/EmptyState";
import { Table } from "../components/Table";
import { Header } from "../layout/Header";
import { formatDate, nullable } from "../utils/format";

export function BatchDetailPage() {
  const navigate = useNavigate();
  const params = useParams();
  const batchId = Number(params.batchId);
  const [batch, setBatch] = useState<GeneratedBatchDetail | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function loadBatch(): Promise<void> {
    if (!Number.isInteger(batchId)) {
      setError("Invalid batch id.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      setBatch(await getBatchDetail(batchId));
    } catch (requestError) {
      setBatch(null);
      setError(getErrorMessage(requestError));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void loadBatch();
  }, [batchId]);

  return (
    <section>
      <Header
        title={`Batch #${Number.isInteger(batchId) ? batchId : ""}`}
        description="Сводка партии и все сгенерированные SHPI."
        actions={
          <div className="inline-actions">
            <Button icon={<RefreshCw size={15} />} loading={loading} onClick={loadBatch}>
              Refresh
            </Button>
            {batch ? (
              <Button
                icon={<FileText size={15} />}
                variant="primary"
                onClick={() => navigate(`/app/pdf/${batch.id}`)}
              >
                PDF / Print
              </Button>
            ) : null}
          </div>
        }
      />

      {error ? <div className="alert alert-danger">{error}</div> : null}
      {loading ? <div className="inline-loader">Loading batch...</div> : null}

      {!loading && !batch ? (
        <EmptyState title="Batch not found" description="Откройте существующий batch из History." />
      ) : null}

      {batch ? (
        <div className="stack">
          <div className="panel">
            <div className="result-header">
              <Badge variant="brand">{batch.package_type}</Badge>
              <Badge variant="neutral">{batch.status}</Badge>
              <Badge variant="success">{batch.quantity} items</Badge>
            </div>
            <dl className="summary-grid">
              <div>
                <dt>Department ID</dt>
                <dd>{nullable(batch.department_id)}</dd>
              </div>
              <div>
                <dt>Generated by</dt>
                <dd>{nullable(batch.generated_by)}</dd>
              </div>
              <div>
                <dt>Generated at</dt>
                <dd>{formatDate(batch.generated_at)}</dd>
              </div>
              <div>
                <dt>Source</dt>
                <dd>{nullable(batch.source)}</dd>
              </div>
              <div>
                <dt>First barcode</dt>
                <dd className="mono">{batch.first_barcode}</dd>
              </div>
              <div>
                <dt>Last barcode</dt>
                <dd className="mono">{batch.last_barcode}</dd>
              </div>
              <div className="wide">
                <dt>Notes</dt>
                <dd>{nullable(batch.notes)}</dd>
              </div>
            </dl>
          </div>

          <div className="panel">
            <h2>Barcodes</h2>
            <Table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>SHPI</th>
                  <th>Sequence</th>
                  <th>Printed</th>
                  <th>Printed at</th>
                  <th>Generated at</th>
                </tr>
              </thead>
              <tbody>
                {batch.barcodes.map((barcode, index) => (
                  <tr key={barcode.id}>
                    <td>{index + 1}</td>
                    <td className="mono">{barcode.barcode}</td>
                    <td className="mono">{barcode.sequence_number}</td>
                    <td>
                      <Badge variant={barcode.printed ? "success" : "neutral"}>
                        {barcode.printed ? "Printed" : "Not printed"}
                      </Badge>
                    </td>
                    <td>{formatDate(barcode.printed_at)}</td>
                    <td>{formatDate(barcode.generated_at)}</td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </div>
        </div>
      ) : null}
    </section>
  );
}
