server:
  port: ${SERVER.PORT}
  servlet:
    context-path: ${SERVER.SERVLET.CONTEXTPATH}

spring:
  jackson:
    time-zone: Asia/Oral
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
      url: jdbc:postgresql://${APP.POSTGREDB.HOST}:${APP.POSTGREDB.PORT}/${APP.POSTGREDB.NAME}
      username: ${APP.POSTGREDB.USER}
      password: ${APP.POSTGREDB.PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5 # Минимальное количество подключений в пуле
        maximum-pool-size: 20 # Максимальное количество подключений в пуле
        connection-timeout: 120000 # Время ожидания соединения (в миллисекундах)
        idle-timeout: 300000 # Время ожидания простоя соединения перед его закрытием (в миллисекундах)
        max-lifetime: 1800000 # Максимальное время жизни соединения (в миллисекундах)
        validation-timeout: 3000 # Тайм-аут проверки соединения перед использованием
        initialization-fail-timeout: -1 # Авто-переподключение в случае неудачного старта (значение -1)
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${KEYCLOAK.ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK.ISSUER_URI}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK.CLIENT_ID}
            client-secret: ${KEYCLOAK.CLIENT_SECRET}
            scope: openid
            provider: keycloak
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: ${KEYCLOAK.GRANT_TYPE}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK.ISSUER_URI}

keycloak:
  logout-url: ${KEYCLOAK.LOGOUT_URL}
  token-uri: ${KEYCLOAK.ISSUER_URI}${KEYCLOAK.TOKEN_URI:/protocol/openid-connect/token}
  client-id: ${KEYCLOAK.CLIENT_ID:admin_cli}
  client-secret: ${KEYCLOAK.CLIENT_SECRET:a6d75fa9-722c-466f-b3ba-ad8b13411cf1}
  issuer-uri: ${KEYCLOAK.ISSUER_URI}

logging:
  level:
    org.flywaydb.core: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

config:
  front-url: ${FRONT_URL}